const actionTypes = {
  LOGIN: "LOGIN",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGOUT: "LOGOUT",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  VERIFY_SUCCESS: "VERIFY_SUCCESS",

  GET_POSTS: "GET_POSTS",
  EDIT_POST: "EDIT_POST",
  RESET_POST: "RESET_POST",
  GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
  GET_POSTS_LIMIT_ADMIN: "GET_POSTS_LIMIT_ADMIN",

  GET_NEW_POST: "GET_NEW_POST",
  GET_OUTSTANDING_POSTS: "GET_OUTSTANDING_POSTS",

  GET_CATEGORIES: "GET_CATEGORIES",
  GET_PRICES: "GET_PRICES",
  GET_AREAS: "GET_AREAS",
  GET_PROVINCES: "GET_PROVINCES",

  // USER
  GET_CURRENT_USER: "GET_CURRENT_USER",
};

export default actionTypes;
